- platform: template
  sensors:
    home_watts_total:
      friendly_name: 'Home Power Total'
      unit_of_measurement: "W"
      value_template: "{{ states('sensor.home_energy_meter_power')|round + states('sensor.home_energy_meter_power_2')|round }}"
    home_current_total:
      friendly_name: 'Home Current Total'
      unit_of_measurement: "A"
      value_template: "{{ states('sensor.home_energy_meter_current')|round + states('sensor.home_energy_meter_current_2')|round }}"
    home_energy_total:
      friendly_name: 'Home Energy Total'
      unit_of_measurement: "kWh"
      value_template: "{{ states('sensor.home_energy_meter_energy')|round + states('sensor.home_energy_meter_energy_2')|round }}"
    climate_main_heat_set_point:
      friendly_name: 'Heat Set Point'
      unit_of_measurement: '°F'
      value_template: '{{ states.climate.main_thermostat_heating_1.attributes.temperature }}'
    door_garage_state:
      friendly_name: 'Door Garage'
      value_template: >-
          {%- if is_state("sensor.garage_door_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.garage_door_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.garage_door_raw', '0') %}
             mdi:garage
          {% elif is_state('sensor.garage_door_raw', '255') %}
             mdi:garage-open
          {% else %}
             mid:help
          {% endif %}
    door_craft_to_patio_state:
      friendly_name: 'Door Craft to Patio'
      value_template: >-
          {%- if is_state("sensor.door_craft_room_to_patio_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.door_craft_room_to_patio_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.door_craft_room_to_patio_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.door_craft_room_to_patio_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    door_craft_to_drive_state:
      friendly_name: 'Door Craft to Drive'
      value_template: >-
          {%- if is_state("sensor.craft_room_to_driveway_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.craft_room_to_driveway_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.craft_room_to_driveway_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.craft_room_to_driveway_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    door_basement_state:
      friendly_name: 'Door Basement'
      value_template: >-
          {%- if is_state("sensor.door_basement_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.door_basement_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.door_basement_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.door_basement_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    door_garage_to_den_state:
      friendly_name: 'Door Garage to Den'
      value_template: >-
          {%- if is_state("sensor.door_garage_to_den_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.door_garage_to_den_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.door_garage_to_den_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.door_garage_to_den_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    door_front_state:
      friendly_name: 'Door Front'
      value_template: >-
          {%- if is_state("sensor.door_front_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.door_front_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.door_front_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.door_front_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    door_back_sliding_state:
      friendly_name: 'Door Back Sliding'
      value_template: >-
          {%- if is_state("sensor.door_back_sliding_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.door_back_sliding_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.door_back_sliding_raw', '0') %}
             mdi:door-closed
          {% elif is_state('sensor.door_back_sliding_raw', '255') %}
             mdi:door-open
          {% else %}
             mid:help
          {% endif %}
    window_craft_room_state:
      friendly_name: 'Window Craft Room'
      value_template: >-
          {%- if is_state("sensor.window_craft_room_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.window_craft_room_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.window_craft_room_raw', '0') %}
             mdi:window-closed
          {% elif is_state('sensor.window_craft_room_raw', '255') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_den_state:
      friendly_name: 'Window Den'
      value_template: >-
          {%- if is_state("sensor.window_den_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.window_den_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.window_den_raw', '0') %}
             mdi:window-closed
          {% elif is_state('sensor.window_den_raw', '255') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_kitchen_state:
      friendly_name: 'Window Kitchen State'
      value_template: >-
          {%- if is_state("sensor.window_kitchen_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.window_kitchen_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.window_kitchen_raw', '0') %}
             mdi:window-closed
          {% elif is_state('sensor.window_kitchen_raw', '255') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_front_east_state:
      friendly_name: 'Window Front East'
      value_template: >-
          {%- if is_state("sensor.window_lr_east_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.window_lr_east_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.window_lr_east_raw', '0') %}
             mdi:window-closed
          {% elif is_state('sensor.window_lr_east_raw', '255') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_front_west_state:
      friendly_name: 'Window Front West'
      value_template: >-
          {%- if is_state("sensor.window_lr_west_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.window_lr_west_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.window_lr_west_raw', '0') %}
             mdi:window-closed
          {% elif is_state('sensor.window_lr_west_raw', '255') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    chest_freezer_state:
      friendly_name: 'Chest Freezer'
      value_template: >-
          {%- if is_state("sensor.chest_freezer_raw", "0") -%}
              Closed
          {%- elif is_state("sensor.chest_freezer_raw", "255") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    safe_state:
      friendly_name: 'Safe State'
      value_template: >-
          {%- if is_state("binary_sensor.safe", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.safe", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    nick_phone_wifi_state:
      friendly_name: 'Nick Phone Wifi'
      value_template: >-
          {%- if is_state("device_tracker.nick_phone", "home") -%}
              Connected
          {%- else -%}
              Not Connected
          {%- endif -%}
      icon_template: >-
          {% if is_state('device_tracker.nick_phone', 'home') %}
             mdi:cellphone-wireless
          {% else %}
             mdi:cellphone
          {% endif %}
    shannon_phone_wifi_state:
      friendly_name: 'Shannon Phone Wifi'
      value_template: >-
          {%- if is_state("device_tracker.shannon_phone", "home") -%}
              Connected
          {%- else -%}
              Not Connected
          {%- endif -%}
      icon_template: >-
          {% if is_state('device_tracker.shannon_phone', 'home') %}
             mdi:cellphone-wireless
          {% else %}
             mdi:cellphone
          {% endif %}
    outside_humidity:
      friendly_name: "Outside Humidity"
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.sensor.pws_relative_humidity.state|float >= 0 and states.sensor.pws_relative_humidity.state|float <= 100 -%}
             {{(states.sensor.pws_relative_humidity.state)}}
          {%- else -%}
             nan
          {%- endif -%}   
    brian_humidity:
      friendly_name: "Brian Humidity"
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.sensor.pws_relative_humidity_2.state|float >= 0 and states.sensor.pws_relative_humidity_2.state|float <= 100 -%}
             {{(states.sensor.pws_relative_humidity_2.state)}}
          {%- else -%}
             nan
          {%- endif -%}
    guy_humidity:
      friendly_name: "Guy Humidity"
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.sensor.pws_relative_humidity_3.state|float >= 0 and states.sensor.pws_relative_humidity_3.state|float <= 100 -%}
             {{(states.sensor.pws_relative_humidity_3.state)}}
          {%- else -%}
             nan
          {%- endif -%}
    outside_temp:
      friendly_name: "Outside Temperature"
      unit_of_measurement: '°F'
      value_template: >-
          {%- if states.sensor.pws_temp_f.state|float >= -50 and states.sensor.pws_temp_f.state|float <= 150 -%}
             {{(states.sensor.pws_temp_f.state)}}
          {%- else -%}
             nan
          {%- endif -%}   
    brian_temp:
      friendly_name: "Brian Temperature"
      unit_of_measurement: '°F'
      value_template: >-
          {%- if states.sensor.pws_temp_f_2.state|float >= -50 and states.sensor.pws_temp_f_2.state|float <= 150 -%}
             {{(states.sensor.pws_temp_f_2.state)}}
          {%- else -%}
             nan
          {%- endif -%}
    guy_temp:
      friendly_name: "Guy Temperature"
      unit_of_measurement: '°F'
      value_template: >-
          {%- if states.sensor.pws_temp_f_3.state|float >= -50 and states.sensor.pws_temp_f_3.state|float <= 150 -%}
             {{(states.sensor.pws_temp_f_3.state)}}
          {%- else -%}
             nan
          {%- endif -%}
    master_real_temp:
      friendly_name: "Master Real Temp"
      unit_of_measurement: '°F'
      value_template: >-
          {%- if states.sensor.master_temperature.state|float >= 40 and states.sensor.master_temperature.state|float <= 90 -%}
             {{(states.sensor.master_temperature.state)}}
          {%- else -%}
             nan
          {%- endif -%}
    weather_alert:
      friendly_name: "Weather Alert"
      value_template: >-
          {%- if states.sensor.pws_alerts.attributes.type != null -%}
             {{(states.sensor.pws_alerts.attributes.type)}}
          {%- else -%}
             nan
          {%- endif -%}
    shelley_duration_to_home:
      value_template: >-
        {{ states.sensor.shelley_location_to_home.attributes.duration }}
    shelley_current_location:
      value_template: >-
        {% if states.sensor.shelley_location_to_home.state %}{{ states.sensor.shelley_location_to_home.attributes.origin_addresses | replace("['","") | replace("']","")}}{% endif %}
    dan_duration_to_home:
      value_template: >-
        {{ states.sensor.dan_location_to_home.attributes.duration }}
    dan_current_location:
      value_template: >-
        {% if states.sensor.dan_location_to_home.state %}{{ states.sensor.dan_location_to_home.attributes.origin_addresses | replace("['","") | replace("']","")}}{% endif %}

    main_thermostat_fan_mode:
      friendly_name: Fan Mode
      value_template: >-
        {{ states.climate.main_thermostat_heating_1.attributes.fan_mode }}

    io_latency_min:
      value_template: "{% set list = states.sensor.io_latency.state.split('|') %} {{ list[0] }}"
      friendly_name: 'IO Latency Min'
      unit_of_measurement: 'usec'
    io_latency_avg:
      value_template: "{% set list = states.sensor.io_latency.state.split('|') %} {{ list[1] }}"
      friendly_name: 'IO Latency Avg'
      unit_of_measurement: 'usec'
    io_latency_max:
      value_template: "{% set list = states.sensor.io_latency.state.split('|') %} {{ list[2] }}"
      friendly_name: 'IO Latency Max'
      unit_of_measurement: 'usec'
    io_latency_sd:
      value_template: "{% set list = states.sensor.io_latency.state.split('|') %} {{ list[3] }}"
      friendly_name: 'IO Latency SD'
      unit_of_measurement: 'usec'

    # USED FOR WAN BANDWIDTH MONITORING #
    snmp_wan_in:
      value_template: "{% set list = states.sensor.snmp_sophos_wan_traffic.state.split('|') %} {{ list[0] }}"
    snmp_wan_out:
      value_template: "{% set list = states.sensor.snmp_sophos_wan_traffic.state.split('|') %} {{ list[1] }}"
    internet_speed_in:
      friendly_name: 'Internet Speed IN'
      value_template: '{{ ((states.input_number.internet_traffic_delta_in.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'
    internet_speed_out:
      friendly_name: 'Internet Speed OUT'
      value_template: '{{ ((states.input_number.internet_traffic_delta_out.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'