- platform: template
  sensors:
    server_rack_watts:
      friendly_name: 'Server Rack'
      unit_of_measurement: "W"
      value_template: '{% if states.switch.server_rack_68.state %}{{ states.switch.server_rack_68.attributes.current_power_w|round }}{% endif %}'
    home_watts:
      friendly_name: 'Home Power'
      unit_of_measurement: "W"
      value_template: '{{ states.sensor.home_26.attributes.current_power_w|round }}'
    ac_watts:
      friendly_name: 'AC Power'
      unit_of_measurement: "W"
      value_template: '{{ states.sensor.ac_10.attributes.current_power_w|round }}'
    furnace1_watts:
      friendly_name: 'Furnace1 Power'
      unit_of_measurement: "W"
      value_template: '{{ states.sensor.furnace1_13.attributes.current_power_w|round }}'
    furnace2_watts:
      friendly_name: 'Furnace2 Power'
      unit_of_measurement: "W"
      value_template: '{{ states.sensor.furnace2_16.attributes.current_power_w|round }}'
    dryer_watts:
      friendly_name: 'Dryer Power'
      unit_of_measurement: "W"
      value_template: '{{ states.sensor.dryer_6.attributes.current_power_w|round }}'
    hot_water_heater_watts:
      friendly_name: 'Hot Water Heater'
      unit_of_measurement: "W"
      value_template: '{% if states.switch.hot_water_heater_19.state %}{{ states.switch.hot_water_heater_19.attributes.current_power_w|round }}{% endif %}'
    climate_main_temperature:
      friendly_name: 'Target Temperature'
      unit_of_measurement: '°F'
      value_template: '{% if states.climate.main_thermostat_39.state %}{{ states.climate.main_thermostat_39.attributes.temperature }}{% endif %}'
    climate_main_temperature2:
      friendly_name: 'Inside Temperature'
      unit_of_measurement: '°F'
      value_template: '{% if states.climate.main_thermostat_39.state %}{{ states.climate.main_thermostat_39.attributes.current_temperature }}{% endif %}'
    climate_main_battery:
      friendly_name: 'Thermostat'
      #unit_of_measurement: '%'
      value_template: '{% if states.climate.main_thermostat_39.state %}{{ states.climate.main_thermostat_39.attributes.battery_level }}{% endif %}'
    climate_main_operating_state:
      friendly_name: 'Operating State'
      value_template: >
        {% if states.climate.main_thermostat_39.state %}{{ states.climate.main_thermostat_39.attributes.operation_mode | replace("(","") | replace(")","") | replace(",","") | replace("'","") }}{% endif %}
    climate_main_fan_state:
      friendly_name: 'Fan Mode'
      value_template: '{% if states.climate.main_thermostat_39.state %}{{ states.climate.main_thermostat_39.attributes.fan_mode }}{% endif %}'
    leak_hot_water_heater_battery:
      friendly_name: 'Leak Hot Water'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.leak_water_heater_21.state %}{{ states.binary_sensor.leak_water_heater_21.attributes.battery_level }}{% endif %}'
    leak_sump_pump_battery:
      friendly_name: 'Leak Sump Pump'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.leak_sump_pump_43.state %}{{ states.binary_sensor.leak_sump_pump_43.attributes.battery_level }}{% endif %}'
    leak_wet_corner_battery:
      friendly_name: 'Leak Wet Corner'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.leak_wet_corner_44.state %}{{ states.binary_sensor.leak_wet_corner_44.attributes.battery_level }}{% endif %}'
    door_basement_battery:
      friendly_name: 'Door Basement'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_basement_52.state %}{{ states.binary_sensor.door_basement_52.attributes.battery_level }}{% endif %}'
    door_garage_to_den_battery:
      friendly_name: 'Door Garage to Den'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_garage_to_den_53.state %}{{ states.binary_sensor.door_garage_to_den_53.attributes.battery_level }}{% endif %}'
    door_front_battery:
      friendly_name: 'Door Front'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_front_97.state %}{{ states.binary_sensor.door_front_97.attributes.battery_level }}{% endif %}'
    door_back_sliding_battery:
      friendly_name: 'Door Back Sliding'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_back_sliding_99.state %}{{ states.binary_sensor.door_back_sliding_99.attributes.battery_level }}{% endif %}'
    window_den_battery:
      friendly_name: 'Window Den'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.window_den_96.state %}{{ states.binary_sensor.window_den_96.attributes.battery_level }}{% endif %}'
    window_front_east_battery:
      friendly_name: 'Window Front East'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.window_lr_east_104.state %}{{ states.binary_sensor.window_lr_east_104.attributes.battery_level }}{% endif %}'
    window_front_west_battery:
      friendly_name: 'Window Front West'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.window_lr_west_113.state %}{{ states.binary_sensor.window_lr_west_113.attributes.battery_level }}{% endif %}'
    window_kitchen_battery:
      friendly_name: 'Window Kitchen'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.window_kitchen_100.state %}{{ states.binary_sensor.window_kitchen_100.attributes.battery_level }}{% endif %}'
    window_craft_room_battery:
      friendly_name: 'Window Craft Room'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.window_craft_room_114.state %}{{ states.binary_sensor.window_craft_room_114.attributes.battery_level }}{% endif %}'
    door_craft_to_patio:
      friendly_name: 'Door Craft to Patio'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_craft_to_patio_133.state %}{{ states.binary_sensor.door_craft_to_patio_133.attributes.battery_level }}{% endif %}'
    door_craft_to_drive:
      friendly_name: 'Door Craft to Drive'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.door_craft_to_drive_134.state %}{{ states.binary_sensor.door_craft_to_drive_134.attributes.battery_level }}{% endif %}'
    gecko_battery:
      friendly_name: 'Gecko Sensor'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.geckos_154.state %}{{ states.binary_sensor.geckos_154.attributes.battery_level }}{% endif %}'
    server_rack_battery:
      friendly_name: 'Server Rack Sensor'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.server_rack_status_63.state %}{{ states.binary_sensor.server_rack_status_63.attributes.battery_level }}{% endif %}'
    chest_freezer_battery:
      friendly_name: 'Chest Freezer Sensor'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.chest_freezer_145.state %}{{ states.binary_sensor.chest_freezer_145.attributes.battery_level }}{% endif %}'
    den_climate_battery:
      friendly_name: 'Den Sensor'
      #unit_of_measurement: '%'
      value_template: '{% if states.binary_sensor.den_sensor_158.state %}{{ states.binary_sensor.den_sensor_158.attributes.battery_level }}{% endif %}'
    door_craft_to_patio_state:
      friendly_name: 'Door Craft to Patio'
      value_template: >-
          {%- if is_state("binary_sensor.door_craft_to_patio_133", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_craft_to_patio_133", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    door_craft_to_drive_state:
      friendly_name: 'Door Craft to Drive'
      value_template: >-
          {%- if is_state("binary_sensor.door_craft_to_drive_134", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_craft_to_drive_134", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    door_basement_state:
      friendly_name: 'Door Basement'
      value_template: >-
          {%- if is_state("binary_sensor.door_basement_52", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_basement_52", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    door_garage_to_den_state:
      friendly_name: 'Door Garage to Den'
      value_template: >-
          {%- if is_state("binary_sensor.door_garage_to_den_53", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_garage_to_den_53", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    door_front_state:
      friendly_name: 'Door Front'
      value_template: >-
          {%- if is_state("binary_sensor.door_front_97", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_front_97", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    door_back_sliding_state:
      friendly_name: 'Door Back Sliding'
      value_template: >-
          {%- if is_state("binary_sensor.door_back_sliding_99", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.door_back_sliding_99", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    window_craft_room_state:
      friendly_name: 'Window Craft Room'
      value_template: >-
          {%- if is_state("binary_sensor.window_craft_room_114", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.window_craft_room_114", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.binary_sensor.window_craft_room_114', 'off') %}
             mdi:window-closed
          {% elif is_state('binary_sensor.window_craft_room_114', 'on') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_den_state:
      friendly_name: 'Window Den'
      value_template: >-
          {%- if is_state("binary_sensor.window_den_96", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.window_den_96", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.binary_sensor.window_den_96', 'off') %}
             mdi:window-closed
          {% elif is_state('binary_sensor.window_den_96', 'on') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_kitchen_state:
      friendly_name: 'Window Kitchen State'
      value_template: >-
          {%- if is_state("binary_sensor.window_kitchen_100", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.window_kitchen_100", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.binary_sensor.window_kitchen_100', 'off') %}
             mdi:window-closed
          {% elif is_state('binary_sensor.window_kitchen_100', 'on') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_front_east_state:
      friendly_name: 'Window Front East'
      value_template: >-
          {%- if is_state("binary_sensor.window_lr_east_104", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.window_lr_east_104", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.binary_sensor.window_lr_east_104', 'off') %}
             mdi:window-closed
          {% elif is_state('binary_sensor.window_lr_east_104', 'on') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    window_front_west_state:
      friendly_name: 'Window Front West'
      value_template: >-
          {%- if is_state("binary_sensor.window_lr_west_113", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.window_lr_west_113", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
      icon_template: >-
          {% if is_state('sensor.binary_sensor.window_lr_west_113', 'off') %}
             mdi:window-closed
          {% elif is_state('binary_sensor.window_lr_west_113', 'on') %}
             mdi:window-open
          {% else %}
             mid:help
          {% endif %}
    chest_freezer_state:
      friendly_name: 'Chest Freezer'
      value_template: >-
          {%- if is_state("binary_sensor.chest_freezer_145", "off") -%}
              Closed
          {%- elif is_state("binary_sensor.chest_freezer_145", "on") -%}
              Open
          {%- else -%}
              FAILED
          {%- endif -%}
    nick_phone_wifi_state:
      friendly_name: 'Nick Phone Wifi'
      value_template: >-
          {%- if is_state("device_tracker.nick_phone", "home") -%}
              Connected
          {%- else -%}
              Not Connected
          {%- endif -%}
      icon_template: >-
          {% if is_state('device_tracker.nick_phone', 'home') %}
             mdi:cellphone-wireless
          {% else %}
             mdi:cellphone
          {% endif %}
    shannon_phone_wifi_state:
      friendly_name: 'Shannon Phone Wifi'
      value_template: >-
          {%- if is_state("device_tracker.shannon_phone", "home") -%}
              Connected
          {%- else -%}
              Not Connected
          {%- endif -%}
      icon_template: >-
          {% if is_state('device_tracker.shannon_phone', 'home') %}
             mdi:cellphone-wireless
          {% else %}
             mdi:cellphone
          {% endif %}
